# Generated by Django 4.2 on 2024-05-07 11:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0004_alter_carphoto_image_alter_carvideo_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_cost', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(1000)])),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rent', to='car.car')),
            ],
        ),
    ]
