# Generated by Django 4.2 on 2024-05-07 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent_invest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rent',
            options={'default_related_name': 'rent', 'verbose_name': 'Аренда'},
        ),
        migrations.AlterModelTable(
            name='rent',
            table='rent',
        ),
    ]
