# Generated by Django 4.2 on 2024-05-07 12:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car', '0005_alter_carvideo_video'),
        ('car_rent_invest', '0002_alter_rent_options_alter_rent_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='currency',
            field=models.CharField(
                default='₽', max_length=3, verbose_name='Валюта'),
        ),
        migrations.CreateModel(
            name='UserRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Начало аренды')),
                ('date_to', models.DateField(verbose_name='До какого числа аренда.')),
                ('rent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 to='car_rent_invest.rent', verbose_name='Аренда')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to=settings.AUTH_USER_MODEL, verbose_name='Арендатор')),
            ],
            options={
                'verbose_name': 'Аренда',
                'db_table': 'user_rent',
                'default_related_name': 'rent',
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_link', models.URLField(unique=True,
                 verbose_name='Отслеживание местоположения автомобиля')),
                ('interest_rate', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(
                    100), django.core.validators.MinValueValidator(15)], verbose_name='Процентная ставка')),
                ('currency', models.CharField(default='₽',
                 max_length=3, verbose_name='Валюта')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='car.car', verbose_name='Инвестиция')),
            ],
        ),
    ]
