# Generated by Django 4.2 on 2024-05-07 12:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_rent_invest', '0003_rent_currency_userrent_investment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrent',
            options={'default_related_name': 'user_rent',
                     'verbose_name': 'Аренда'},
        ),
        migrations.AlterField(
            model_name='rent',
            name='daily_cost',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(
                100000), django.core.validators.MinValueValidator(1000)], verbose_name='Стоимость в день'),
        ),
        migrations.CreateModel(
            name='UserInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(
                    verbose_name='Начало инвестирования.')),
                ('date_to', models.DateField(
                    verbose_name='До какого числа инверстировал.')),
                ('sum', models.PositiveIntegerField(validators=[
                 django.core.validators.MinValueValidator(100000)], verbose_name='Вложенная сумма')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='car_rent_invest.investment', verbose_name='Инвестиция')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to=settings.AUTH_USER_MODEL, verbose_name='Инвестор')),
            ],
            options={
                'verbose_name': 'Инвестиция',
                'db_table': 'user_investment',
                'default_related_name': 'user_investment',
            },
        ),
    ]
