# Generated by Django 4.2 on 2024-05-13 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_car_daily_rent_car_price_car_short_description_and_more'),
        ('car_rent_invest', '0005_alter_userinvestment_options_alter_userrent_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrent',
            name='rent',
        ),
        migrations.AddField(
            model_name='userrent',
            name='car',
            field=models.ForeignKey(
                default=6, on_delete=django.db.models.deletion.CASCADE, to='car.car', verbose_name='Арендовано'),
        ),
        migrations.DeleteModel(
            name='Rent',
        ),
    ]
