# Generated by Django 4.2 on 2024-05-13 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_car_daily_rent_car_price_car_short_description_and_more'),
        ('car_rent_invest', '0006_remove_userrent_rent_userrent_car_delete_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrent',
            name='car',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='car.car', verbose_name='Арендовано'),
        ),
    ]
