# Generated by Django 4.2 on 2024-05-14 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_carphoto_is_preview'),
        ('car_rent_invest', '0007_alter_userrent_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrent',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='car.car', unique=True, verbose_name='Арендовано'),
        ),
    ]
