# Generated by Django 4.2 on 2024-05-14 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_carphoto_is_preview'),
        ('car_rent_invest', '0008_alter_userrent_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrent',
            name='car',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to='car.car', verbose_name='Арендовано'),
        ),
    ]
