# Generated by Django 4.2 on 2024-05-15 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent_invest', '0011_remove_userinvestment_investment_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userrent',
            table='user_rent',
        ),
    ]
