# Generated by Django 4.2 on 2024-05-15 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0023_alter_carvideo_video'),
        ('car_rent_invest', '0012_alter_userrent_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrent',
            name='car',
            field=models.OneToOneField(error_messages={'blank': 'Такая аренда уже существует.', 'invalid': 'Такая аренда уже существует.'}, on_delete=django.db.models.deletion.CASCADE, to='car.car', verbose_name='Машина'),
        ),
    ]
