# Generated by Django 4.2 on 2024-05-16 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0023_alter_carvideo_video'),
        ('car_rent_invest', '0013_alter_userrent_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrent',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car', verbose_name='Машина'),
        ),
    ]
