# Generated by Django 4.2 on 2024-05-16 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent_invest', '0014_alter_userrent_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrent',
            old_name='date_to',
            new_name='end_rent',
        ),
        migrations.RenameField(
            model_name='userrent',
            old_name='date_from',
            new_name='start_rent',
        ),
    ]
