# Generated by Django 4.2 on 2024-05-30 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent_invest', '0016_userrent_complited'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrent',
            name='distance',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(300000), django.core.validators.MinValueValidator(1)], verbose_name='Пройденое расстояние за период аренды'),
        ),
    ]
