# Generated by Django 4.2 on 2024-06-01 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent_invest', '0017_userrent_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrent',
            name='distance',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(300000), django.core.validators.MinValueValidator(1)], verbose_name='Пройденое расстояние(км)'),
        ),
    ]
