# Generated by Django 4.2 on 2024-05-07 08:07

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название автомобиля')),
                ('color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None, unique=True, verbose_name='Цвет')),
                ('description', models.TextField(verbose_name='Описание')),
                ('year_release', models.CharField(max_length=20, verbose_name='Год выпуска')),
                ('gas', models.CharField(choices=[('GAS', 'cas'), ('GASOLINE', 'gasoline')], default='GAS', max_length=16, verbose_name='Топливо')),
                ('license_plate', models.CharField(max_length=8, unique=True, verbose_name='Гос. номер')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='VIN')),
                ('pts', models.CharField(max_length=17, unique=True, verbose_name='ПТС')),
                ('sts', models.CharField(max_length=17, unique=True, verbose_name='СТС)')),
                ('status', models.CharField(choices=[('TECHNICAL_SERVICE', 'technical_service'), ('REPAIR', 'repair'), ('WORK', 'work'), ('ON_PARKING', 'on_parking')], default='ON_PARKING', max_length=17, verbose_name='Статус машины')),
                ('technical_services', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'default_related_name': 'cars',
            },
        ),
        migrations.CreateModel(
            name='CarVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='car.car')),
            ],
        ),
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='car.car')),
            ],
        ),
    ]
