# Generated by Django 4.2 on 2024-05-07 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='gas',
            field=models.CharField(choices=[('GAS', 'газ'), ('GASOLINE', 'бензин')], default='GAS', max_length=16, verbose_name='Топливо'),
        ),
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(blank=True, max_length=8, unique=True, verbose_name='Гос. номер'),
        ),
        migrations.AlterField(
            model_name='car',
            name='pts',
            field=models.CharField(blank=True, max_length=17, unique=True, verbose_name='ПТС'),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('TECHNICAL_SERVICE', 'техобслуживание'), ('REPAIR', 'на ремонте'), ('WORK', 'работает'), ('ON_PARKING', 'на стоянке')], default='ON_PARKING', max_length=17, verbose_name='Статус машины'),
        ),
        migrations.AlterField(
            model_name='car',
            name='sts',
            field=models.CharField(blank=True, max_length=17, unique=True, verbose_name='СТС'),
        ),
        migrations.RemoveField(
            model_name='car',
            name='technical_services',
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, max_length=17, unique=True, verbose_name='VIN'),
        ),
        migrations.AlterField(
            model_name='carphoto',
            name='image',
            field=models.ImageField(unique=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='carvideo',
            name='video',
            field=models.FileField(unique=True, upload_to='videos/'),
        ),
        migrations.CreateModel(
            name='CarTechnicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_service', models.DateField()),
                ('complited', models.BooleanField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car', verbose_name='Автомобиль')),
                ('technical_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.technicalservice', verbose_name='Техническое обслуживание.')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='technical_services',
            field=models.ManyToManyField(help_text='Удерживайте Ctrl для выбора нескольких вариантов', through='car.CarTechnicalService', to='car.technicalservice', verbose_name='Обслуживания'),
        ),
    ]
