# Generated by Django 4.2 on 2024-05-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_technicalservice_alter_car_gas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='pts',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='ПТС'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='VIN'),
        ),
    ]
