# Generated by Django 4.2 on 2024-05-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_car_pts_alter_car_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carphoto',
            name='image',
            field=models.ImageField(unique=True, upload_to='images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='carvideo',
            name='video',
            field=models.FileField(unique=True, upload_to='videos/', verbose_name='Видео'),
        ),
    ]
