# Generated by Django 4.2 on 2024-05-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_alter_carphoto_image_alter_carvideo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carvideo',
            name='video',
            field=models.URLField(unique=True, verbose_name='Видео'),
        ),
    ]
