# Generated by Django 4.2 on 2024-05-08 09:20

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_alter_carvideo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='Гос. номер'),
        ),
        migrations.AlterField(
            model_name='car',
            name='sts',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='СТС'),
        ),
    ]
