# Generated by Django 3.2.16 on 2024-05-08 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_alter_car_color_alter_car_license_plate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carphoto',
            options={'default_related_name': 'photos'},
        ),
        migrations.AlterModelOptions(
            name='carvideo',
            options={'default_related_name': 'videos'},
        ),
        migrations.RenameField(
            model_name='carphoto',
            old_name='image',
            new_name='photo',
        ),
        migrations.AlterField(
            model_name='carphoto',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='car.car'),
        ),
    ]
