# Generated by Django 3.2.16 on 2024-05-08 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_auto_20240508_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartechnicalservice',
            options={'default_related_name': 'car_technical_services'},
        ),
        migrations.AlterField(
            model_name='cartechnicalservice',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_technical_services', to='car.car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='cartechnicalservice',
            name='technical_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_technical_services', to='car.technicalservice', verbose_name='Техническое обслуживание.'),
        ),
    ]
