# Generated by Django 3.2.16 on 2024-05-08 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_alter_technicalservice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartechnicalservice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='technicalservice',
            options={'default_related_name': 'technical_services', 'verbose_name': 'Техническое обслуживание.', 'verbose_name_plural': 'Технические обслуживания'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='technical_services',
        ),
        migrations.AddField(
            model_name='car',
            name='technical_service',
            field=models.ManyToManyField(help_text='Удерживайте Ctrl для выбора нескольких вариантов', related_name='cars', through='car.CarTechnicalService', to='car.TechnicalService', verbose_name='Обслуживания'),
        ),
        migrations.AlterField(
            model_name='cartechnicalservice',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='cartechnicalservice',
            name='technical_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.technicalservice', verbose_name='Техническое обслуживание.'),
        ),
    ]
