# Generated by Django 4.2 on 2024-05-14 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_carphoto_is_preview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartechnicalservice',
            options={'default_related_name': 'technical_services', 'verbose_name': 'Обслуживание', 'verbose_name_plural': 'Обслуживания'},
        ),
    ]
