# Generated by Django 4.2 on 2024-05-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0013_alter_cartechnicalservice_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartechnicalservice',
            constraint=models.UniqueConstraint(fields=('car', 'technical_service'), name='unique_car_and_technical_service'),
        ),
    ]
