# Generated by Django 4.2 on 2024-05-15 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0017_alter_car_technical_service_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'default_related_name': 'cars', 'ordering': ('name',), 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
    ]
