# Generated by Django 4.2 on 2024-05-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0020_alter_car_technical_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalservice',
            name='name',
            field=models.CharField(max_length=254, null=True, verbose_name='Название обслуживания'),
        ),
    ]
