# Generated by Django 4.2 on 2024-05-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0021_alter_technicalservice_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalservice',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Название обслуживания'),
        ),
    ]
