# Generated by Django 4.2 on 2024-05-16 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0023_alter_carvideo_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide', models.BooleanField(default=False, verbose_name='Скрыть карточку из каталога')),
                ('new', models.BooleanField(default=False, verbose_name='Бейджик')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
                'default_related_name': 'card',
            },
        ),
    ]
