# Generated by Django 4.2 on 2024-05-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0024_carcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcard',
            name='new',
            field=models.BooleanField(default=False, verbose_name='Бейджик новое'),
        ),
    ]
