# Generated by Django 4.2 on 2024-05-17 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0026_car_technical_characteristic'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalservice',
            name='description',
            field=models.TextField(default='Без описания', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TechnicalServiceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(blank=True, null=True, unique=True, verbose_name='Видео')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.cartechnicalservice')),
            ],
            options={
                'default_related_name': 'services_videos',
            },
        ),
        migrations.CreateModel(
            name='TechnicalServicePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(unique=True, upload_to='images/', verbose_name='Фото')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.cartechnicalservice')),
            ],
            options={
                'default_related_name': 'services_photos',
            },
        ),
    ]
