# Generated by Django 4.2 on 2024-05-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0027_technicalservice_description_technicalservicevideo_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartechnicalservice',
            name='unique_car_and_technical_service',
        ),
        migrations.AlterField(
            model_name='carphoto',
            name='photo',
            field=models.ImageField(unique=True, upload_to='cars/images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='technicalservicephoto',
            name='photo',
            field=models.ImageField(unique=True, upload_to='technical_services/images/', verbose_name='Фото'),
        ),
    ]
