# Generated by Django 4.2 on 2024-05-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0032_cartechnicalservice_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartechnicalservice',
            options={'default_related_name': 'car_technical_services', 'ordering': ('date_service',), 'verbose_name': 'Обслуживание', 'verbose_name_plural': 'Обслуживания'},
        ),
        migrations.AlterField(
            model_name='cartechnicalservice',
            name='date_service',
            field=models.DateField(auto_now_add=True, verbose_name='Дата технического обслуживания.'),
        ),
    ]
