# Generated by Django 4.2 on 2024-05-22 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0033_alter_cartechnicalservice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartechnicalservice',
            options={'default_related_name': 'car_technical_services', 'ordering': ('-date_service',), 'verbose_name': 'Обслуживание', 'verbose_name_plural': 'Обслуживания'},
        ),
    ]
