# Generated by Django 4.2 on 2024-05-24 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0034_alter_cartechnicalservice_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TechnicalServiceVideo',
        ),
    ]
