# Generated by Django 4.2 on 2024-05-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0035_delete_technicalservicevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartechnicalservice',
            name='scheduled_date',
            field=models.DateField(
                default='2024-05-23', verbose_name='Запланированная дата обслуживания.'),
            preserve_default=False,
        ),
    ]
