# Generated by Django 4.2 on 2024-05-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0036_cartechnicalservice_scheduled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartechnicalservice',
            name='scheduled_date',
            field=models.DateField(null=True, verbose_name='Запланированная дата обслуживания.'),
        ),
    ]
