# Generated by Django 4.2 on 2024-05-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0037_alter_cartechnicalservice_scheduled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartechnicalservice',
            name='scheduled_date',
            field=models.DateField(default='2024-05-23', verbose_name='Запланированная дата обслуживания.'),
            preserve_default=False,
        ),
    ]
