# Generated by Django 4.2 on 2024-05-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0038_alter_cartechnicalservice_scheduled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartechnicalservice',
            name='date_service',
            field=models.DateField(verbose_name='Дата технического обслуживания.'),
        ),
    ]
