# Generated by Django 4.2 on 2024-06-01 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0040_remove_cartechnicalservice_unique_car_and_technical_service_and_date_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartechnicalservice',
            name='complited',
        ),
    ]
