# Generated by Django 4.2 on 2024-06-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0041_remove_cartechnicalservice_complited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalservice',
            name='name',
            field=models.CharField(max_length=254, unique=True, verbose_name='Название обслуживания'),
        ),
    ]
