# Generated by Django 4.2 on 2024-06-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0042_alter_technicalservice_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartechnicalservice',
            name='comment',
            field=models.TextField(blank=True, default='Без комментариев.', verbose_name='Комментарий к обслуживанию.'),
        ),
    ]
