# Generated by Django 4.2 on 2024-06-06 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0043_alter_cartechnicalservice_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartechnicalservice',
            options={'default_related_name': 'car_technical_services', 'ordering': ('-date_service',), 'verbose_name': 'Техническое обслуживание', 'verbose_name_plural': 'Технические обслуживания'},
        ),
        migrations.AlterModelOptions(
            name='technicalservice',
            options={'default_related_name': 'technical_services', 'verbose_name': 'Oбслуживание', 'verbose_name_plural': 'Oбслуживания'},
        ),
    ]
