# Generated by Django 4.2 on 2024-06-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0044_alter_cartechnicalservice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technicalservice',
            options={'default_related_name': 'technical_services', 'ordering': ('name',), 'verbose_name': 'Oбслуживание', 'verbose_name_plural': 'Oбслуживания'},
        ),
        migrations.AlterField(
            model_name='cartechnicalservice',
            name='date_service',
            field=models.DateField(null=True, verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='cartechnicalservice',
            name='scheduled_date',
            field=models.DateField(verbose_name='Запланированная дата'),
        ),
    ]
