# Generated by Django 4.2 on 2024-06-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0045_alter_technicalservice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartechnicalservice',
            name='comment',
            field=models.TextField(blank=True, default='Без комментариев.', null=True, verbose_name='Комментарий к обслуживанию.'),
        ),
    ]
