# Generated by Django 4.2 on 2024-06-20 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0047_uploadphoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadPhoto',
        ),
    ]
