# Generated by Django 4.2 on 2024-06-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0048_delete_uploadphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(unique=True, upload_to='upload_files', verbose_name='Фото')),
            ],
        ),
    ]
