# Generated by Django 4.2 on 2024-06-26 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0049_uploadphoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadPhoto',
        ),
    ]
