# Generated by Django 4.2 on 2024-05-07 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_phone_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=20, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^((+7|7|8)+([0-9]){10})$', 'Номер должен начинаться с 7, +7, 8 и содержать после этого 10 цифр.')], verbose_name='Телефон'),
        ),
    ]
