# Generated by Django 4.2 on 2024-05-08 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_options_alter_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^((\\+7|7|8)+([0-9]){10})$', 'Номер должен начинаться с 7, +7, 8 и содержать после этого 10 цифр.')], verbose_name='Номер телефона'),
        ),
    ]
