# Generated by Django 4.2 on 2024-05-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notification',
            field=models.CharField(choices=[('SMS', 'sms'), ('WITHOUT_NOTIFICATIONS', 'без уведомлений')], default='SMS', max_length=22, verbose_name='Уведомление'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=150, verbose_name='Пароль'),
        ),
    ]
