# Generated by Django 4.2 on 2024-05-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_notification_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='notification',
            field=models.CharField(choices=[('SMS', 'sms'), ('WITHOUT_NOTIFICATIONS', 'без уведомлений')], default='SMS', max_length=22, verbose_name='Уведомления'),
        ),
    ]
