# Generated by Django 4.2 on 2024-05-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='notification',
            field=models.CharField(choices=[('SMS', 'смс'), ('TELEGRAM', 'телеграм'), ('WHATSAPP', 'ватсап'), ('WITHOUT_NOTIFICATIONS', 'без уведомлений')], default='SMS', max_length=22, verbose_name='Уведомления'),
        ),
    ]
