# Generated by Django 4.2 on 2024-05-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'администратор'), ('CLIENT', 'пользователь'), ('MECHANIC', 'механик')], default='CLIENT', max_length=16, verbose_name='Роль пользователя'),
        ),
    ]
